# .upptimerc.yml
owner: testtestestestsdgss
repo: status
user-agent: testtestestestsdgss  # recommended

# Run the uptime workflow every 10 minutes (5 min is the minimum if you prefer)
workflowSchedule:
  uptime: "*/10 * * * *"        # cannot be faster than every 5 minutes
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"

# Optional: slow down between checks if target sites are touchy (ms)
# delay: 200

sites:
  - name: Example 1
    url: https://a1limobus.com
    method: GET
    expectedStatusCodes:
      - 200
      - 301
      - 302
      - 403
  - name: Example 2
    url: https://a1tampalimo.com
    method: GET
    expectedStatusCodes:
      - 200
      - 301
      - 302
      - 403
  # …we’ll bulk-add thousands below

status-website:
  name: Your Status
  # If you use a custom domain, set CNAME:
  # cname: status.yourdomain.com
  # If not, set baseUrl to your repo name:
  baseUrl: /status
  navbar:
    - title: Status
      href: /
    # If you shard into multiple repos later, add links here to each shard’s page
