name: Token test
on: workflow_dispatch
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - run: |
          git config user.name "upptime-bot"
          git config user.email "actions@github.com"
          date > token-test.txt
          git add token-test.txt
          git commit -m "token-test"
          git push
